model_name = "LSTM_model_0"
MSELoss_criterion="mean"
sequence_length = 12
batch_size = 64
input_dim = 1
output_dim = 1
hidden_dim = 4
layer_dim = 1
learning_rate = 0.03
epochs = 10
patience = 10
min_delta = 0.001
n_iters_eval = 100
